version: '3.7'
services:
  gitpitch:
    image: knsit/gitpitch:latest
    environment:
      - "GP_GITHUB_AS_DEFAULT=true"
    ports:
      - 9000:9000
  gh-terraform:
    image: hashicorp/terraform:0.12.31
    working_dir: /work
    volumes:
      - ${PWD}/scripts/tf/github.com:/work
      - ${HOME}/.aws:/root/.aws
    environment:
      - TF_VAR_github_token
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  python-da:
    build: ./scripts/dashboard
    volumes:
      - ${PWD}:/app
    environment:
      - GOOGLE_KEY
      - SHEET_KEY
      - GH_USER
      - GH_TOKEN
  aws-cli:
    image: amazon/aws-cli
    volumes:
      - ${PWD}:/app
    environment:
      - SLACK_WEBHOOK
      - SLACK_CHANNEL
      - PUBLISH_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    entrypoint:
      - bash
  exercises:
    image: devopsacademyau/reviewer:latest
    volumes:
      - ${PWD}/students:/students
    environment:
      - GH_USER
