# See https://github.com/actions/labeler
name: ReviewerGit
on:
  pull_request:
    paths:
    - 'scripts/reviewers/git/**/*'
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Arrange
      run: scripts/reviewers/git/arrange.sh
    - name: Act
      run: scripts/reviewers/git/act.sh
    - name: Assert
      run: scripts/reviewers/git/assert.sh
      