name: reviewer-publish
on:
  pull_request:
    paths:
    - 'reviewer/exercises/git04/**/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            git04:
              - 'reviewer/exercises/git04/**/*'
            git03:
              - 'reviewer/exercises/git04/**/*'
      
      # - name: Extract data from yaml file
      #   id: data
      #   run: |
      #     echo "::set-output name=myitems::$(cat ./config.yaml | yq e '.spokes.[] | keys | join(",")' - | jq -Rsc '. / "\n" - [""]')"          


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker meta - git04
        id: meta_git04
        if: steps.changes.outputs.git04 == 'true'
        uses: docker/metadata-action@v4
        with:
          images: |
            devopsacademyau/reviewer
          tags: |
            type=ref,event=pr,prefix=git04-pr-
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push - git04
        uses: docker/build-push-action@v3
        if: steps.changes.outputs.git04 == 'true'
        with:
          push: true
          context: ./reviewer
          file: ./reviewer/Dockerfile.python
          build-args: |
            EXERCISE=git04
          tags: ${{ steps.meta_git04.outputs.tags }}

      - name: Docker meta - git03
        id: meta_git03
        if: steps.changes.outputs.git03 == 'true'
        uses: docker/metadata-action@v4
        with:
          images: |
            devopsacademyau/reviewer
          tags: |
            type=ref,event=pr,prefix=git03-pr-
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push - git03
        uses: docker/build-push-action@v3
        if: steps.changes.outputs.git03 == 'true'
        with:
          push: true
          context: ./reviewer
          file: ./reviewer/Dockerfile.python
          build-args: |
            EXERCISE=git03
          tags: ${{ steps.meta_git03.outputs.tags }}